### ISSUE TITLE
No RangeItem?

### ISSUE THREAD

**Issue by erotavlas** [mbuchetics/RangeTree#11]
I just installed v1.0.5 from NuGet, but there is no object called RangeItem, nor is there RangeItemComparer.  Could not use the sample code to create a new tree.

    var tree = new RangeTree<int, RangeItem>(new RangeItemComparer());

**Comment by apacha** [comment]
Well. The classes `RangeItem` and `RangeItemComparer` are not predefined. You have to implement the respective interfaces to host the data, that you actually want to store in the RangeTree. I've updated the Readme with a simple example and for future clarification.
Please note, that https://github.com/mbuchetics/RangeTree/tree/master/RangeTreeExamples also contains more sophisticated implementations for those two classes.
