### ISSUE TITLE
Query on empty rTree causes ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by erotavlas** [mbuchetics/RangeTree#14]
I removed all items from the rTree, but when I try to query the rTree for an item it gives the following error.

> An unhandled exception of type 'System.ArgumentOutOfRangeException' occurred in mscorlib.dll
> Additional information: Index was out of range. Must be non-negative and less than the size of the collection.

I think this is a bug.  It should return zero items from the query, not throw an error.  

I'll surround with a check for number of items > 0 before attempting query for now.

**Comment by apacha** [comment]
Fixed in v.1.0.6
