### ISSUE TITLE
RangeTree.Add(IEnumerable<T> items) is inconsistent with standard AddRange(IEnumerable<T>)

### ISSUE THREAD

**Issue by rzippo** [mbuchetics/RangeTree#17]
I know it's a minor issue, but the method is easy to miss.

**Comment by apacha** [comment]
Thanks for reporting the issues. Feel free to create a pull-request and I will merge it as soon as possible. Note that I am very busy at the moment but will try to do it as soon as possible

**Comment by apacha** [comment]
The public interface will change in version 2 and add<IEnumerable> will be removed.
