### ISSUE TITLE
Improperly Named

### ISSUE THREAD

**Issue by AndrewDavis** [mbuchetics/RangeTree#24]
This is an [Interval Tree](https://en.wikipedia.org/wiki/Interval_tree), not a [Range Tree](https://en.wikipedia.org/wiki/Range_tree), so it should be renamed.

**Comment by apacha** [comment]
Thank you for the comment. Could you elaborate a bit more on the specifics, please? I quickly scanned the linked pages and either I didn't fully understand the difference or I'm missing some piece of information that would make this project an Interval tree.

**Comment by AndrewDavis** [comment]
Umm...

https://github.com/mbuchetics/RangeTree/blob/master/README.md

**Comment by AndrewDavis** [comment]
The difference between the two from a conceptual standpoint appears to be that an IntervalTree deals with intervals in the actual data whereas a RangeTree does not.

**Comment by apacha** [comment]
Ok, I agree. Will take a look at it soon and rename it accordingly. If you want, you can do it too and file a pull request.

**Comment by apacha** [comment]
I assume that the project started as Range Tree and then evolved into an Interval Tree.

**Comment by apacha** [comment]
Solved with releases of versions 2.1.0 and 3.0.0
