### ISSUE TITLE
Min/Max values incorrect

### ISSUE THREAD

**Issue by nordic81** [mbuchetics/RangeTree#28]
If I add an interval to the tree that spans around the center value of the tree providing a new over all minimum and or maximum key value, the provided min/max values of the tree are wrong.
The root node will only look in the outer subtrees, if these exist and ignore the center items.

**Comment by apacha** [comment]
Thanks for reporting this issue. Can you give us a minimum executable example, so we can reproduce and fix the issue?

**Comment by nordic81** [comment]
i was just trying to push the tests and the fix in a separate branch, but obviously I'm not contributor enough :D

`
[Test]
public void GettingMin_Mixed()
{
    var tree = new IntervalTree<int, int>
    {
        { 2, 3, -1 },
        { 8, 9, -1 },
        { 1, 10, -1 },
    };

    var min = tree.Min;

    Assert.That(min, Is.EqualTo(1));
}
        
[Test]
public void GettingMax_Mixed()
{
    var tree = new IntervalTree<int, int>
    {
        { 1, 10, -1 },
        { 2, 3, -1 },
        { 4, 5, -1 },
        { 8, 9, -1 },
    };

    var max = tree.Max;

    Assert.That(max, Is.EqualTo(10));
}
`

Suggested fix:
IntervalTreeNode.cs
`
public TKey Max { get; private set; } = default(TKey);

public TKey Min { get; private set; } = default(TKey);
`

IntervalTreeNode cosntructor:
`
// the median is used as center value
if (endPoints.Count > 0)
{
    Min = endPoints[0];
    center = endPoints[endPoints.Count / 2];
    Max = endPoints[endPoints.Count - 1];
}
`

**Comment by apacha** [comment]
Thanks for the example. I see your point. 

Yes, you do not have push-permissions to this repository. The correct flow, how you can contribute directly by opening a Pull-Request can be found here: https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request.

If you create a PR, I can review and merge it.

**Comment by nordic81** [comment]
overread the part with the fork. thanks. :)

**Comment by nordic81** [comment]
any updates on this matter? :angel:

**Comment by apacha** [comment]
Fixed in 3.0.1
