### ISSUE TITLE
Return range-value pair on querry

### ISSUE THREAD

**Issue by lamest** [mbuchetics/RangeTree#30]
Why isn't it returns the range itself on querry, only values? its like reducing functionality for no good reason

**Comment by lamest** [comment]
or, even better, we can return subtree

**Comment by apacha** [comment]
Thanks for your PR. I looked at it, but I can't see why this would be a good idea to return something that you have inserted into the method. Additionally, this interface change causes lots of additional statements  (e.g., .Value, .Select(...)) being required when using it as well as being incompatible with previous versions, requiring all users to change their code.

What exactly is your requirement? Maybe there is a better solution with the existing interface, e.g. use A as key and Pair<A,B> as value?

**Comment by apacha** [comment]
As there is no new information, I'm closing this ticket and the PR
