### ISSUE TITLE
Range tree + dapper

### ISSUE THREAD

**Issue by suprunka** [mbuchetics/RangeTree#33]
Is it possible that query result returns range tree? Is there any mapping that we can use?

**Comment by fravelgue** [comment]
It should be possible in some cases, but I think there is not any type handler available in Dapper. Do you need to store a complete Range-tree in a binary column or RangeValuePair per row?

**Comment by apacha** [comment]
I don't know how to do this. If you want to create appropriate extensions, please open a PR, otherwise I'm closing this issue now.
