### ISSUE TITLE
Deserialization issue- invalid Add method

### ISSUE THREAD

**Issue by suprunka** [mbuchetics/RangeTree#34]
IntervalTree.IntervalTree`cannot be deserialized since it does not have a valid Add method with parameter of type 'IntervalTree.RangeValuePair`.
Would that be possible to add 'Add' method with empty body/ exception so it is possible to serialize the object?

**Comment by apacha** [comment]
Can you please specify exactly what you tried to get this error? 
If you have specific ideas, feel free to open a PR and when we might be able to add that functionality.

**Comment by apacha** [comment]
Closing this as there is no more information from the author. If you have more information, feel free to open a new issue. Thanks for your contribution.
