### ISSUE TITLE
Question: ideas for finding the unoccupied intervals?

### ISSUE THREAD

**Issue by CharlieDigital** [mbuchetics/RangeTree#35]
Given two numbers `lower` and `upper`, is there a more efficient mechanism to find all of the unoccupied intervals?

```
I ==========
0 --
1       ----    
```
In this example, 
- [1,2] is occupied.
- [3,6] is unoccupied.
- [7-10] is occupied.

A naive solution is to simply iterate through the numbers between `lower` (1) and `upper` (10) while tracking the start and end of each unoccupied interval by querying for the number.

But I wonder if there is a more clever way to "invert" the intervals or maintain a separate tree that has the unoccupied intervals for fast retrieval.

Would love to hear some thoughts.

**Comment by apacha** [comment]
It might not be a big improvement, but you could at least read the occupied ranges and skip to the next one, for which you don't have any information:

For your example:
1. Check 1 -> Returns [1, 2]
2. Skip to end of the of the (largest) interval that was returned and add +1 = 3
3. Test 3 -> No result (memorize)
4. Test 4 -> No result (memorize)
5. Test 5 -> No result (memorize)
6. Test 6 -> No result (memorize)
7. Test 7 -> returns [7,10] -> Done 
8. Print all memorized values: [3,4,5,6]

Alternatively you might be able to do something like an inversion tree with a fixed maximum range that starts with a single element [min, max] that represents a "hole". Upon adding an element to that tree, you query that interval and "cut" the whole into multiple "holes". 

For your example

```
Start
I ==========
H ---------- (hole 1) - at the beginning our tree is empty, so the hole covers the entire interval

To insert the first real element E1 [1,2] which represents an occupied range:
- Retrieve all elements in that interval -> Hole 1 [1, 10]
- Cut the hole into two, Hole 2 [] (empty left side) and Hole 3 [3, 10]
- Delete the old Hole 1 and insert Hole 2 (won't do anything) and Hole 3

I ==========
H   -------- (hole 3)

Let's insert something in the middle to show what I mean by cutting into two: 
Insert the element E2 [6,7], which represents another occupied range:
- Retrieve all elements in that interval -> Hole 3 [3, 10]
- Cut the hole into two, Hole 4 [3,5] and Hole 5 [8, 10]
- Delete the old Hole 3 and insert Hole 4 and Hole 5

I ==========
H   ---      (hole 4)
H        --- (hole 5)

To get all holes, simply print out all elements that are in the inversion-tree, as it only holds "holes".
```

Of course this requires a bit more thoughts about overlaps etc., but it might be a starting point.

If you find a good solution and want to share it, I would be more than happy to see a PR.

**Comment by CharlieDigital** [comment]
The inverted tree was what I was thinking about as well and basically trade a bit of memory for a bit of speed.

I will let you know; currently early in the process of evaluating whether the interval tree is the right data structure for a problem I'm working on.
