### ISSUE TITLE
IntervalTree for 2D points

### ISSUE THREAD

**Issue by HelloHumans13** [mbuchetics/RangeTree#37]
Works great with 1D. How to use with 2D like with System.Numerics.Vector2.

**Comment by apacha** [comment]
I think what you are looking for is something like https://en.wikipedia.org/wiki/R-tree not an Interval tree

**Comment by HelloHumans13** [comment]
Sorry to trouble you (kinda new to data structure) but shouldn't Interval tree support [2 dimensions](https://www.wikiwand.com/en/Interval_tree#/Higher_dimensions_2). I'm trying to find all rectangles which overlap query rectangle. I prefer Interval tree over R tree as i-tree has worst case performance of O(log n) whereas r-tree as O(n).

**Comment by apacha** [comment]
If you want to nest interval trees, you can do so (the value would then be another Interval tree). I just recommend that you have a good look at R-trees (or R*-trees). They are exactly what you want if you want to have overlapping queries with rectangular regions and more efficient than nested interval trees.

**Comment by apacha** [comment]
And the expected performance for R*-trees is not that bad, as it will try to re-balance it. In general, your performance with an R*-Tree will also be O(log n)
