### ISSUE TITLE
Check out forks for more bugfixes

### ISSUE THREAD

**Issue by apacha** [mbuchetics/RangeTree#4]
Check out these forks, as they might contain bugfixes for known issues:
- https://github.com/jandorfer/RangeTree/commits/master
- https://github.com/Mistuke/RangeTree/commits/master
- https://github.com/Ttxman/RangeTree/commits/master

**Comment by erdomke** [comment]
Just for fun, I finished my own overhaul over at https://github.com/erdomke/RangeTree

**Comment by apacha** [comment]
Looks like you've put a lot of work into this. That's great. I will check it out and try to merge your overhaul.
