### ISSUE TITLE
UInt128 lacks ToString override

### ISSUE THREAD

**Issue by ststeiger** [mbuchetics/RangeTree#5]
File:
https://github.com/somdoron/NaCl.net/blob/master/nacl.net/UInt128.cs
Sadly, the ToString override on UInt128 is very absent. 
I implemented it. 

I also added 
        : System.IComparable
        , System.IComparable&lt;UInt128&gt;
        , System.Collections.Generic.IComparer&lt;UInt128&gt;
        , System.IEquatable&lt;UInt128&gt;
and operators ==, !=, &lt;, &gt;, &lt;=, &gt;=
See
https://github.com/ststeiger/RangeTree/blob/master/RangeTree/UInt128.cs
for full reference

        // http://stackoverflow.com/questions/11656241/how-to-print-uint128-t-number-using-gcc#answer-11659521
        public override string ToString()
        {
            uint[] buf = new uint[40];
            ulong ulOne = 1;
            
            uint i, j, m = 39;
            for (i = 64; i-- > 0; )
            {
                int usi = (int)i;
                // UInt128 n = value;
                // int carry = !!(n & ((UInt128)1 << i));
                ulong carry = (this.High & (ulOne << usi));
                carry = carry != 0 ? (ulong)1 : (ulong)0; // ToBool
                carry = carry == 0 ? (ulong)1 : (ulong)0; // ! 
                carry = carry == 0 ? (ulong)1 : (ulong)0; // ! 

                for (j = 39; j-- > m + 1 || carry != 0; )
                {
                    ulong d = 2 * buf[j] + carry;
                    carry = d > 9 ? (ulong)1 : (ulong)0;
                    buf[j] = carry != 0 ? (char)(d - 10) : (char)d;
                } // Next j 
                m = j;
            } // Next i 

            for (i = 64; i-- > 0; )
            {
                int usi = (int)i;
                ulong carry = (this.Low & (ulOne << usi));
                carry = carry != 0 ? (ulong)1 : (ulong)0; // ToBool
                carry = carry == 0 ? (ulong)1 : (ulong)0; // ! 
                carry = carry == 0 ? (ulong)1 : (ulong)0; // ! 

                for (j = 39; j-- > m + 1 || carry != 0; )
                {
                    ulong d = 2 * buf[j] + carry;
                    carry = d > 9 ? (ulong)1 : (ulong)0;
                    buf[j] = carry != 0 ? (char)(d - 10) : (char)d;
                } // Next j 
                m = j;
            } // Next i 

            System.Text.StringBuilder sb = new System.Text.StringBuilder();
            
            bool hasFirstNonNull = false;
            for (int k = 0; k < buf.Length - 1; ++k)
            { 
                
                if(hasFirstNonNull || buf[k] != 0)
                {
                    hasFirstNonNull = true;
                    sb.Append(buf[k].ToString());
                } // End if(hasFirstNonNull || buf[k] != 0)

            } // Next k 

            if (sb.Length == 0)
                sb.Append('0');
            
            string s = sb.ToString();
            sb.Length = 0;
            sb = null;
            return s;
        }

**Comment by apacha** [comment]
Not really related to this repo. Is it?

**Comment by ststeiger** [comment]
You're right, sorry - apparently I was in the wrong tab when posting. 
Used RangeTree to lookup IPv6 ranges when Geolocating. 
IPv6 = 128 Bit ==> uint128
