### ISSUE TITLE
Using via Nuget, it installs many dependencies not needed due compatibility

### ISSUE THREAD

**Issue by fravelgue** [mbuchetics/RangeTree#9]
It seems you could target multiples frameworks:
`<TargetFrameworks>netstandard1.2;netstandard2.0;net45</TargetFrameworks>`

Thanks very much

**Comment by apacha** [comment]
Will try to rebuild with multiple targets and republish.

**Comment by apacha** [comment]
Done - please verify and open another issue, if 1.0.4 did not fix your issue.
